### ISSUE TITLE
Samurai Ghost display issues

### ISSUE THREAD

**Issue by StephanKuwabara** [agg23/openfpga-pcengine#10]
### Version (or build number)

0.1.1

### Steps to reproduce

-Start the game
-Start moving horizontally

### Actual Behavior

the screen rapidly flashes black as I move, and sometimes the screen resolution changes.  

It's hard to capture the resolution changes on video because it happens so quickly, but I'll send a link to a short video I took of the issue

https://drive.google.com/file/d/16Mj9shv-0AFlqHr1LgSsNB5w0xzh1xDj/view?usp=sharing

**Comment by agg23** [comment]
Looks like I fixed this with fbfa03c06d624c0597f0732721e7f78b4e3120df. Release coming soon
