### ISSUE TITLE
Button II Turbo resets value when quitting the core.

### ISSUE THREAD

**Issue by ifighftdragons** [agg23/openfpga-pcengine#13]
### Version (or build number)

0.2.0

### Actual Behavior

Button II Turbo resets set value when quitting the core.
I set the value to 2 (Max), and it resets back to 0 every time I turn off the Pocket, or quit the core.

Button I Turbo works as expected, and retains the set value after quitting and restarting the core.

**Comment by agg23** [comment]
Sorry about that. Fixed with 0.2.1
