### ISSUE TITLE
atlantean 

### ISSUE THREAD

**Issue by gregmariotti** [agg23/openfpga-pcengine#15]
### Version (or build number)

0.21

### Steps to reproduce

when you launch the game, you get the following error message regarding a save file.

![B436A050-9251-4FB7-88CB-7C462B193B9D](https://user-images.githubusercontent.com/115591167/198421917-f87760b3-f0f1-431f-ab69-4c7e70a5d5a8.jpeg)

### Expected Behavior

normal title screen. 

### Actual Behavior

see screenshot.

**Comment by agg23** [comment]
If you previously tried to open Atlantean, you need to delete the save file it created. This issue (#5) was fixed in 0.2.0

**Comment by gregmariotti** [comment]
so sorry. I missed that. thanks so much
