### ISSUE TITLE
Repo Title Says "SNES for the Analogue Pocket"

### ISSUE THREAD

**Issue by Noname1122** [agg23/openfpga-pcengine#16]
### Ask a question

Hi there,

This didn't feel right to report as a "bug".

Here on GitHub, the repo is named "SNES for the Analogue Pocket". For findability reasons, it should probably be PC Engine or TurboGrafx. I swear I'm trying to find a way not to sound sarcastic as I type this, haha. <3 <3

**Comment by agg23** [comment]
That's really weird. I must have copied the description from the SNES core?

Thanks for the heads up
