### ISSUE TITLE
SuperGrafx not supported?

### ISSUE THREAD

**Issue by ifighftdragons** [agg23/openfpga-pcengine#3]
### Ask a question

Will SuperGrafx be supported? Couldn't get 1941 or Aldynes to run.

**Comment by agg23** [comment]
Sorry, should have put this in the README. SuperGrafx is on hold until a chip32 bug is fixed.

**Comment by agg23** [comment]
Released in 196b62dd705ab858dcebe63fba4340318a6b57df
