### ISSUE TITLE
Original composite color pallette 

### ISSUE THREAD

**Issue by IndoJimbo** [agg23/openfpga-pcengine#6]
Request for a toggle in the core options for Raw RGB color or original composite color.

**Comment by mario-64** [comment]
I too would love to see this feature ported from MiSTer

**Comment by pceDev16** [comment]
Looking at the current palette.mif included in this repo and comparing it against the final palette added to the MiSTer core which emulates the Hardware YUV lookup-table, https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/blob/master/palette.mif, it would appear they are different?

**Comment by agg23** [comment]
What makes you say that? I just checked `src\fpga\core\rtl\palette.mif` against `palette.mif` in the MiSTer repo and they're the same.

**Comment by mario-64** [comment]
I'm confused. The new release mentions adding raw RGB color palette. Is that the one which uses the composite video lookup table? That's what I was looking for. Or does the core use the composite LUT by default?

**Comment by agg23** [comment]
If I understand correctly, the composite palette is used by default, and the RGB palette is activated by the toggle

**Comment by mario-64** [comment]
Ok thanks. Good deal
