### ISSUE TITLE
512x240 mode on Monoscope pattern in 240P Test Suite 1.12 only draws 60% of the screen

### ISSUE THREAD

**Issue by pceDev16** [agg23/openfpga-pcengine#8]
### Version (or build number)

0.1.1

### Steps to reproduce

1. Download 240P Test Suite .pce file from here: https://artemiourbina.itch.io/240p-test-suite
2. Launch Core
3. Load 240P Test Suite rom
4. Enter Test Patterns
5. Scroll down to Monoscope pattern and press the right most button to launch.

Note how only 60% of the screen is used and the pattern is compressed within that area.

### Expected Behavior

The Monoscope pattern should fill the entire screen, when Overscan is disabled of course.

### Actual Behavior

Only 60% of the screen is used and the Monoscope pattern is horizontally compressed to fit within that area. 

If you were using another test pattern (such as the "Grids" pattern) at 512x240 before selecting the Monoscope pattern, the previous pattern will flicker in the empty space on the right of the screen. 

### Additional Context

Great release, super happy to see this on the Pocket!

**Comment by agg23** [comment]
I observed this too. I haven't checked the pixel count yet, but it must not actually be 512 wide, or it's rendering one line that has more pixels than the other lines

**Comment by agg23** [comment]
Yea, just checked. It's only outputting 360 pixels wide. I'm guessing that it actually displays borders around the video, but I cut those off to fit the display better.

**Comment by pceDev16** [comment]
We'd be super interested to test this on some other specific PCE dev created roms for latching tests. Would you be able to cut a release @agg23 ?

**Comment by agg23** [comment]
I can send you a build, but I'm probably not going to release until I have this solved better. I'm building a linebuffer solution that should solve this issue everywhere, rather than my current hacky solution.

**Comment by pceDev16** [comment]
We'd appreciate a build if you could spare the time, is there a doc somewhere about compiling the main branch ourselves?

**Comment by agg23** [comment]
It's easy to build. Download and install Quartus 21.1.1 (you don't need this version, but it's the version I use), follow the [guide to fix the PLL build issue](https://github.com/agg23/analogue-pocket-utils/wiki/Quartus#megafunction-versioning), and press `Start Compilation`.

You'll need to reverse the bitstream (`ap_core.rbf`), for which [Analogue provides a simple reversal tool](https://www.analogue.co/developer/docs/packaging-a-core#creating-a-reversed-rbf).

**Comment by pceDev16** [comment]
Ahh great it's using Quartus.... :( , I'm on macOS so this will be a bit of a thing to setup w Wine or a VM w Parallels. Guess we'll have to wait? Anything we can do to help/test/whatevers?
