### ISSUE TITLE
Ninja Spirit cropped too much at bottom. “Hide Overscan” should be disabled by default. 

### ISSUE THREAD

**Issue by naveedster** [agg23/openfpga-pcengine#9]
See photo of real PC Engine on Sony PVM vs the Pocket: 
![B56D5398-DD87-4148-875B-0A3004D2C09A](https://user-images.githubusercontent.com/80052032/196860273-629644c3-b29d-43cf-b8cd-6a4a10ecf3b9.jpeg)

The year 1990 and the Developer IREM is cut off at the bottom.

**Comment by naveedster** [comment]
@
![Uploading FA6CD5CD-486F-4EB2-8D34-8E4621E9EA5E.jpeg…]()

**Comment by Goldanas** [comment]
Turn off the "Hide Overscan" option in the in the Core Settings.
To some extent that's to simulate what it would have displayed like on a CRT, but many games did display decent information in that space.

**Comment by naveedster** [comment]
There we go! That would fix it. So the real bug here is that “Hide Overscan” should be disabled by default.

**Comment by agg23** [comment]
I disagree. People will complain either way, because overscan was hidden on most TVs, so there's occasionally garbage down there. Pretty strange that PC Engine games don't seem to respect a save zone.

**Comment by SegaSnatcher** [comment]
I already confirmed this with agg23 yesterday, but probably a good idea to relay this information here too. 

The way the port on Pocket is handling hide overscan is not consistent with MiSTer.  The port on Pocket for some reason is shifting the image down when you enable this option which is causing that extra line to be cropped when it doesn't on MiSTer.  

This is how it looks on MiSTer with Hide Overscan enabled.

![DSC00414](https://user-images.githubusercontent.com/36483667/197075079-eb2513aa-49b8-4706-8317-d05aa204d034.JPG)
